# Generated by Django 4.1.1 on 2022-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_product_mst_product_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_date', models.CharField(max_length=25)),
                ('event_information', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=25)),
                ('notice_date', models.DateField(auto_now_add=True)),
                ('notice_information', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Socity_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('house_no', models.CharField(max_length=25)),
                ('Product_image', models.FileField(default='k.jpg', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=25)),
                ('visit_date_and_time', models.CharField(max_length=25)),
                ('exit_time', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchman_name', models.CharField(max_length=25)),
                ('watchman_date_and_time', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_mst',
        ),
    ]
