# Generated by Django 4.1.1 on 2022-11-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_product_image_socity_members_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='socity_members',
            name='password',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
