# Generated by Django 4.1.4 on 2022-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_socity_members_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=25)),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('notice_information', models.CharField(max_length=250)),
            ],
        ),
    ]
